### ISSUE TITLE
module 'sent2vec' has no attribute 'Sent2vecModel'

### ISSUE THREAD

**Issue by mar00nie** [epfml/sent2vec#42]
Hi, I trained a sent2vec model last week and was able to use it for sentence similarity. Today I reran the code in jupyter notebook and the line "model = sent2vec.Sent2vecModel()" produces the error "module 'sent2vec' has no attribute 'Sent2vecModel'". Do you know what the problem is?

**Comment by mpagli** [comment]
Did you try reinstalling the cython module ?

**Comment by mar00nie** [comment]
I recloned the repository and ran all the commands again, and now it works. Thanks.

**Comment by patilaum** [comment]
`Processing /home/aum/ezDI/main_code/sent2vec
Installing collected packages: sent2vec
  Running setup.py install for sent2vec ... done
Successfully installed sent2vec-0.0.0`

**Comment by Stannislav** [comment]
Note that if you install `sent2vec` using
```bash
$ pip install sent2vec
```
then you'll get the wrong package. This is because the package `sent2vec` [on PyPI](https://pypi.org/project/sent2vec/) is a [totally different package with the same name](https://github.com/pdrm83/sent2vec).

The correct way of installing `sent2vec` is to clone their repository here https://github.com/epfml/sent2vec and to follow the instructions in the README file
