### ISSUE TITLE
module 'sent2vec' has no attribute 'Sent2vecModel'

### ISSUE THREAD

**Issue by patilaum** [epfml/sent2vec#61]
Getting the same error #42 and #43  and this is not working for me. The python module is not getting generated. I ran these commands and following file is being produced
sent2vec.cpython-35m-x86_64-linux-gnu.so
and sent to /usr/local/lib/python-3.5/dist-packages/

following is the log of pip3 install .
`Processing /home/aum/ezDI/main_code/sent2vec Installing collected packages: sent2vec Running setup.py install for sent2vec ... done Successfully installed sent2vec-0.0.0`

**Comment by mpagli** [comment]
That's weird, could you try with an anaconda environment (https://www.anaconda.com/distribution/)?

**Comment by Stannislav** [comment]
Note that if you install `sent2vec` using
```bash
$ pip install sent2vec
```
then you'll get the wrong package. This is because the package `sent2vec` [on PyPI](https://pypi.org/project/sent2vec/) is a [totally different package with the same name](https://github.com/pdrm83/sent2vec).

The correct way of installing `sent2vec` is to clone their repository here https://github.com/epfml/sent2vec and to follow the instructions in the README file

**Comment by vishwa795** [comment]
This problem still exists. I am facing the same problem. I have tried re-installing sent2vec repo, but nothing seems to work.
pip install . on sent2vec shows that `sent2vec-0.0.0` is installed but when I do conda list to check sent2vec is not shown there. While executing the script to extract key phrase I get the error saying module `'sent2vec' has no attribute 'Sent2vecModel'`

**Comment by guptaprkhr** [comment]
I think you need to remove the old sent2vec installation first.
