### ISSUE TITLE
[not an issues] Any specific reason to use sent2vec embeddings over fastText embeddings ?

### ISSUE THREAD

**Issue by spate141** [epfml/sent2vec#9]
I was looking at the paper and code. Great work first of all! I have a question in mind, as new fastText library can generate sentence embeddings by averaging word vectors, is there any comparison between fastText and sent2vec in any supervised/unsupervised task?

**Comment by martinjaggi** [comment]
the main difference is that our vectors are trained such that they can be added over variable length sentences/documents. this should make a large difference. we hope to have more comparisons soon. (the approach could potentially even be combined with subword vectors as you mentioned). in the meantime, feel free to run some benchmark directly, for example [sentEval](https://github.com/facebookresearch/SentEval), or   [STS 2017](http://nlp.arizona.edu/SemEval-2017/pdf/SemEval001.pdf).

**Comment by guptaprkhr** [comment]
Hi, 
The fastText sentence embeddings are very much similar to CBOW and Skipgram averaged-embeddings in performance as the word vectors they learn are on a CBOW-ish objective (while exploiting the use of morphology) while our word embeddings are trained for the purpose of getting proper sentence embeddings rather than the word embeddings themselves. As you can see in the paper, our embeddings significantly outperform the sentence embeddings.
